### ISSUE TITLE
你好，可以提供一下数据集的下载链接吗？非常感谢

### ISSUE THREAD

**Issue by Wang-Peicheng** [FeipengMa6/PriSA#2]
作者你好，我从别处下载的MOSEI数据集没有emotion_labels标签，可以提供代码中使用的MOSEI数据集的下载链接吗？万分感谢。

**Comment by FeipengMa6** [comment]
Hi, I have put the MOSEI dataset on [weiyun](https://share.weiyun.com/6zj86Uhn), and now you can download it. I hope this will help you!

**Comment by Wang-Peicheng** [comment]
Thank you very much! I appreciate it！
